//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Code/Input/BowlingInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @BowlingInput : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @BowlingInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""BowlingInput"",
    ""maps"": [
        {
            ""name"": ""BowlingGampley"",
            ""id"": ""bcf25f6d-f6d6-4f0a-bc28-48f85fdf635a"",
            ""actions"": [
                {
                    ""name"": ""DrawDelta"",
                    ""type"": ""Value"",
                    ""id"": ""65f6808a-d4f9-4294-9550-a55023fdb050"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""DrawPosition"",
                    ""type"": ""Value"",
                    ""id"": ""3912d733-1e76-478d-981a-080284c00204"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""PressAction"",
                    ""type"": ""Button"",
                    ""id"": ""2d99bb8e-ee3b-4cad-b1f3-a3ce13758475"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""85de021f-48ad-413f-9f7b-c4412a701d46"",
                    ""path"": ""<Touchscreen>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DrawDelta"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""317238d5-6e75-4694-9a73-d25fe51dc2f3"",
                    ""path"": ""<Pointer>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DrawDelta"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""30e23287-2f7b-4f11-9c8b-dcbd96ba4cd4"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DrawDelta"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""94505c59-48b4-4bed-b032-a88fb3ce2357"",
                    ""path"": ""<Pointer>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DrawPosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""39375556-6b02-4ac2-b5cb-7c90124a6a66"",
                    ""path"": ""<Touchscreen>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DrawPosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""70d35d4b-6883-4855-a5f5-18bd226a4298"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DrawPosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e7ffecb7-fe37-4b33-88a0-67857b2f49d3"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PressAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""051146a9-5d67-4df2-98b7-2f0c71ee3308"",
                    ""path"": ""<Touchscreen>/primaryTouch/tap"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PressAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dd6e3ead-bcb4-4332-bc66-1381f5091706"",
                    ""path"": ""<Pointer>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PressAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // BowlingGampley
        m_BowlingGampley = asset.FindActionMap("BowlingGampley", throwIfNotFound: true);
        m_BowlingGampley_DrawDelta = m_BowlingGampley.FindAction("DrawDelta", throwIfNotFound: true);
        m_BowlingGampley_DrawPosition = m_BowlingGampley.FindAction("DrawPosition", throwIfNotFound: true);
        m_BowlingGampley_PressAction = m_BowlingGampley.FindAction("PressAction", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // BowlingGampley
    private readonly InputActionMap m_BowlingGampley;
    private IBowlingGampleyActions m_BowlingGampleyActionsCallbackInterface;
    private readonly InputAction m_BowlingGampley_DrawDelta;
    private readonly InputAction m_BowlingGampley_DrawPosition;
    private readonly InputAction m_BowlingGampley_PressAction;
    public struct BowlingGampleyActions
    {
        private @BowlingInput m_Wrapper;
        public BowlingGampleyActions(@BowlingInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @DrawDelta => m_Wrapper.m_BowlingGampley_DrawDelta;
        public InputAction @DrawPosition => m_Wrapper.m_BowlingGampley_DrawPosition;
        public InputAction @PressAction => m_Wrapper.m_BowlingGampley_PressAction;
        public InputActionMap Get() { return m_Wrapper.m_BowlingGampley; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(BowlingGampleyActions set) { return set.Get(); }
        public void SetCallbacks(IBowlingGampleyActions instance)
        {
            if (m_Wrapper.m_BowlingGampleyActionsCallbackInterface != null)
            {
                @DrawDelta.started -= m_Wrapper.m_BowlingGampleyActionsCallbackInterface.OnDrawDelta;
                @DrawDelta.performed -= m_Wrapper.m_BowlingGampleyActionsCallbackInterface.OnDrawDelta;
                @DrawDelta.canceled -= m_Wrapper.m_BowlingGampleyActionsCallbackInterface.OnDrawDelta;
                @DrawPosition.started -= m_Wrapper.m_BowlingGampleyActionsCallbackInterface.OnDrawPosition;
                @DrawPosition.performed -= m_Wrapper.m_BowlingGampleyActionsCallbackInterface.OnDrawPosition;
                @DrawPosition.canceled -= m_Wrapper.m_BowlingGampleyActionsCallbackInterface.OnDrawPosition;
                @PressAction.started -= m_Wrapper.m_BowlingGampleyActionsCallbackInterface.OnPressAction;
                @PressAction.performed -= m_Wrapper.m_BowlingGampleyActionsCallbackInterface.OnPressAction;
                @PressAction.canceled -= m_Wrapper.m_BowlingGampleyActionsCallbackInterface.OnPressAction;
            }
            m_Wrapper.m_BowlingGampleyActionsCallbackInterface = instance;
            if (instance != null)
            {
                @DrawDelta.started += instance.OnDrawDelta;
                @DrawDelta.performed += instance.OnDrawDelta;
                @DrawDelta.canceled += instance.OnDrawDelta;
                @DrawPosition.started += instance.OnDrawPosition;
                @DrawPosition.performed += instance.OnDrawPosition;
                @DrawPosition.canceled += instance.OnDrawPosition;
                @PressAction.started += instance.OnPressAction;
                @PressAction.performed += instance.OnPressAction;
                @PressAction.canceled += instance.OnPressAction;
            }
        }
    }
    public BowlingGampleyActions @BowlingGampley => new BowlingGampleyActions(this);
    public interface IBowlingGampleyActions
    {
        void OnDrawDelta(InputAction.CallbackContext context);
        void OnDrawPosition(InputAction.CallbackContext context);
        void OnPressAction(InputAction.CallbackContext context);
    }
}
